service: todo-react-app-backend-try-1
provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-1
functions:
  app:
    handler: server.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true
