name: dev

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-dev:
    name: Build and deploy backend-app dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run:
          npm install
      - name: Check
        run: |
          ls -la
          pwd
          ls -la ~
          ls -la ~/.npm
      - name: Update serverless config
        run: |
          echo {{ parameters.environment }}
          sed -i "s/%env%/{{ parameters.environment }}/g" serverless.yml
          cat serverless.yml
      - name: Configure AWS Credentials
        run:
          ./node_modules/.bin/serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy server app
        run:
          ./node_modules/.bin/serverless deploy
