name: dev

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-dev:
    name: Build backend-app dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packages
        run:
          npm install --save
      - name: Check
        run: |
          ls -la
          pwd
          ls -la ~
      - name: Update serverless config
        run:
          sed -i "s/%env%/{{ parameters.environment }}/g" serverless.yml
      - name: Configure AWS Credentials
        run:
          npm/serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Configure AWS Credentials
        run:
          npm/serverless deploy
